config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/show', as: 'dashboard'

  resources :surveys

  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :journal_entries, except: [:index, :destroy]
  resources :resources, only: [:index]
  resources :types, only: [:show]
  resources :users, only: [:index]

  root to: 'dashboards#show'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :survey_response
  belongs_to :question

  validates :question, :survey_response, :response, presence: true
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :question
  belongs_to :question_group

  validates :text, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :author, class_name: "User"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  belongs_to :question_type
  belongs_to :question_group
  has_many :answer_options, dependent: :destroy

  validates :survey, :text, :question_type, presence: true
end

app/models/question_group.rb
class QuestionGroup < ApplicationRecord
  belongs_to :survey
  has_many :questions, dependent: :destroy
  has_many :answer_options, dependent: :destroy

  validates :description, :survey, presence: true
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
  validates :name, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :resource_topics
  has_many :topics, through: :resource_topics
  has_many :resource_types
  has_many :types, through: :resource_types

  validates :title, presence: true
end

app/models/resource_topic.rb
class ResourceTopic < ApplicationRecord
  belongs_to :topic
  belongs_to :resource
end

app/models/resource_type.rb
class ResourceType < ApplicationRecord
  belongs_to :type
  belongs_to :resource
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :questions, dependent: :destroy
  has_many :question_groups, dependent: :destroy

  validates :author, :name, :description, presence: true
end

app/models/survey_response.rb
class SurveyResponse < ApplicationRecord
  belongs_to :survey
  belongs_to :respondent, class_name: "User"
  has_many :answers, dependent: :destroy

  validates :respondent, :survey, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :resource_topics
  has_many :resources, through: :resource_topics

  validates :title, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :resource_types
  has_many :resources, through: :resource_types

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :journal_entries, foreign_key: :author_id, dependent: :destroy
  has_many :surveys,          foreign_key: :author_id
  has_many :survey_responses, foreign_key: :respondent_id

  def admin?
    role == "admin"
  end

  def intern?
    role == "intern"
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :find_survey, only: [:show, :edit, :update, :destroy]

  def index
    @surveys = Survey.all
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.author = current_user

    if @survey.save
      flash[:success] = "Survey successfully created."
      redirect_to surveys_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @survey.update(survey_params)
      flash[:success] = "Survey successfully updated."
      redirect_to surveys_path
    else
      render :edit
    end
  end

  def destroy
    if @survey.destroy
      flash[:success] = "Survey, questions, and answers successfully deleted."
      redirect_to surveys_path
    else
      render :edit
    end
  end

private

  def find_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit(:name, :description, :active)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def show
    @type = Type.find(params[:id])
    @resources = @type.resources
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interntrak</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div id="navigation">
        <div id="logo-home-link" class="image-link-buttons">
          <%= link_to image_tag("train-track.png", alt: "interntrak-logo"), root_path %>
        </div>
        <div id="user-img-link" class="image-link-buttons">
          <%= link_to image_tag("temp-user-img.png", alt: "user-img"), edit_user_registration_path %>
          <h4 class="user-name">First Last</h4>
        </div>
        <div id="feature-links">
          <div class="feature-link"><%= link_to 'Schedule', '' %></div>
          <div class="feature-link"><%= link_to 'Notes', '' %></div>
          <div class="feature-link"><%= link_to 'Pairing', '' %></div>
          <div class="feature-link"><%= link_to 'Stories', '' %></div>
          <div class="feature-link"><%= link_to 'Assessment', '' %></div>
          <div class="feature-link"><%= link_to 'Resources', resources_path %></div>
        </div>
      </div>
      <div id="right-column">
        <div id="login">
          <% if user_signed_in? %>
            <%= link_to image_tag("settings-icon.png", alt: "settings-icon") %>
            <%= link_to('Sign out', sign_out_path, class: "btn btn__link", :method => :delete) %>
          <% end %>
        </div>
        <div id="content">
          <h3 id="welcome-name">Welcome, First Last.</h3>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/resources/index.html.erb
<h1>Resources</h1>
<% @topics.each do |topic| %>
  <h2>
    <%= topic.title %>
  </h2>
  <p>
    <%= topic.description %>
  </p>
  <ul>
  <% topic.resources.each do |resource| %>
    <li>
      <%= link_to(resource.title, resource.url) %>
      <%= resource.description %>
      <div class="types">
        Types:
        <% resource.types.each do |type| %>
          <%= link_to(type.title, type_path(type)) %>
        <% end %>
      </div>
    </li>
  <% end %>
  </ul>
<% end %>